### PR TITLE
Addresses the issue #102

### PR DESCRIPTION
**Pull request by javaduke**

### CODE REVIEW

**Comment by javaduke** [comment]
@jam01 Now I think this is how it should be done.

**Comment by jam01** [comment]
Hey @javaduke can we check if these tests pass without those changes? I'm not exactly sure if this is a DS or camel issue. The ujson exception is not super clear

**Comment by javaduke** [comment]
I checked, without these changes tests fail, here's why. If you pass a null to the JSON plugin, it properly returns `ujson.Null$.MODULE$` and everything works as expected. But empty strings fail, because they are not valid JSON objects. So we should treat empty strings just like nulls. The issue is that if in Camel you have an API with GET request, the body would be an empty string and even if the DS transformation ignores body completely, it will fail with "exhausted input" exception.

**Comment by jam01** [comment]
Ah... Gotcha. Let me think on this one for a sec ...

**Comment by javaduke** [comment]
Actually - can you please ping me on slack? Let's chat for a few min, there are couple of other things I'd like to discuss

**Comment by javaduke** [comment]
@jam01 Can we touch base really quick today?

**Comment by jam01** [comment]
Sure, gotta check if I still have DS slack access

**Comment by javaduke** [comment]
If not, just send me an email and I will send you zoom invite.

**Pull request merged**
